### ISSUE TITLE
Bad Gateway sometimes (502)

### ISSUE THREAD

**Issue by Blamo27** [mjstealey/wordpress-nginx-docker#17]
Hello,

I have a problem with my wordpress, sometimes there are some 502 bad gateway, access.log :
```
X.X.X.X - - [25/Jan/2019:22:49:05 +0000] "POST /wp-json/alids/v1/extension HTTP/1.1" 200 66 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 OPR/57.0.3098.116"
X.X.X.X  - - [25/Jan/2019:22:49:07 +0000] "POST /wp-json/alids/v1/extension HTTP/1.1" 502 559 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 OPR/57.0.3098.116
```

In the error.log :
```
2019/01/25 22:49:07 [error] 6#6: *102 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 10.255.0.2, server: 178.0.0.1 (hide), request: "POST /wp-json/alids/v1/extension HTTP/1.1", upstream: "fastcgi://10.0.39.2:9000", host: "178.0.0.1 (hide)"
```

I also noticed that on the fpm logs, `/usr/local/sbin/php-fpm` :
```
[25-Jan-2019 22:44:40] NOTICE: Failed implicitly binding to ::, retrying with 0.0.0.0
[25-Jan-2019 22:44:40] ERROR: unable to bind listening socket for address '9000': Address in use (98)
[25-Jan-2019 22:44:40] ERROR: FPM initialization failed
```

Can you please help me ?

Wordpress version: wordpress:php7.2-fpm-alpine

**Comment by Blamo27** [comment]
Solved issue, the problem was caused by alpine ...
I just removed alpine so :
wordpress:php7.2-fpm-alpine -> wordpress:php7.2-fpm
And it works now

**Comment by mjstealey** [comment]
> Solved issue, the problem was caused by alpine ...
> I just removed alpine so :
> wordpress:php7.2-fpm-alpine -> wordpress:php7.2-fpm
> And it works now

Glad to hear it is working for you now.
I've not tried the alpine distribution personally, though in theory it should be equivalent...
Perhaps some kind of transient communication issue between the Nginx container and alpine based Wordpress container at the socket level.

FWIW, there is a newer php7.3-fpm based image out for Wordpress that I'll soon be updating to.

**Comment by Blamo27** [comment]
> Perhaps some kind of transient communication issue between the Nginx container and alpine based Wordpress container at the socket level.

Yes it should be something like that :) 

Nice, I'll test php7.3 fpm then. Thanks.
