### ISSUE TITLE
letsencrypt-renew.sh

### ISSUE THREAD

**Issue by newzealandpaul** [mjstealey/wordpress-nginx-docker#2]
Thanks for creating this, very useful!

Just a quick question, I assume I should be running letsencrypt-renew.sh? Maybe should be added to the README.

**Comment by mjstealey** [comment]
@newzealandpaul - yes, you should be running the `letsencrypt-renew.sh` script periodically to check the status of your certificates and renew them if they are close to expiry.

The script can be run on it's own without having to modify/stop/start any of the other containers. You can either run it manually, or set it up as a cron task that fires every 15 days or so.

You are 100% correct that this should be added to the README... an oversight on my part, and thank you for pointing it out.

**Comment by mjstealey** [comment]
Updated docs to reflect use of `letsencrypt-renew.sh` script merged in PR #3 
Closing
