### ISSUE TITLE
How can i increase post_max_size and upload_max_filesize

### ISSUE THREAD

**Issue by RomeoCovaci** [mjstealey/wordpress-nginx-docker#25]
How can i increase post_max_size and upload_max_filesize? thanks

**Comment by schmiddim** [comment]
-> https://github.com/docker-library/wordpress/issues/10#issuecomment-329332019

**Comment by RomeoCovaci** [comment]
thank you.

**Comment by EchedeyLR** [comment]
Can you confirm if setting re-definitions in .htaccess works too? 

https://github.com/docker-library/wordpress/issues/10#issuecomment-446841644 (the option B)
