### ISSUE TITLE
Warn about EVERYTHING actually being EVERYTHING

### ISSUE THREAD

**Issue by k1sul1** [mjstealey/wordpress-nginx-docker#26]
I've been playing around with this for about 15 minutes now, looks nice. I just skimmed through the README and started testing things. I fucked up about 5 minutes in and I couldn't get WP running without recloning the repo. I did it again soon enough, but this time I noticed the stop-everything-and-remove.sh script, and I ran it.

> Do you really want to stop and remove EVERYTHING?

I've just installed a new machine, and I transferred some docker volumes on it, that I haven't used, _yet_. When I ran the script, I noticed it pruned unused volumes, literally ALL of them. If restoring them wouldn't take about 5 seconds, I would've had a minor heart attack.

I know it says EVERYTHING but I didn't expect it to wipe every volume I have. This is literally the first thing I'm running on docker on this new machine :joy: 

I probably should've checked what the script does before actually running it but it's late and I might've had a few drinks. 

Maybe you could add a few more words to the warning, like "literally every volume that isn't used by a container"?

**Comment by mjstealey** [comment]
@k1sul1 - yeah... everything did mean EVERYTHING w.r.t. volumes.

It's possible that I had a few drinks while composing this repo originally 🍻 

The script was written using my personal notion of having anything I care about persisted to a local directory, and as such I tend to prune everything volume and network wise. I can look at taming the prune to be limited to what would be expected for the example, and leave it up to the user to adapt as needed.

Thanks for the input!

**Comment by k1sul1** [comment]
You're welcome! 

I had to switch to named volumes, as rebuilding images would fail with `PermissionError: [Errno 13] Permission denied: '/project/mysql/wordpress'`. 

Named volumes changed that, haven't had a need to run that script since.

**Comment by mjstealey** [comment]
script has been removed
