### ISSUE TITLE
Unable to renew certificates

### ISSUE THREAD

**Issue by sadesarrollo** [mjstealey/wordpress-nginx-docker#33]
Hi there,

I have been using your project for a Wordpress site I have and it is amazing, thanks so much!

However, when it comes to renew my certificates, I get an **unauthorized** error. I think the file never gets created and so then the acme challenge gets a **404 response**.

Here you can see the script I'm launching for testing purposes (dry-run):

`docker run -t --rm     -v /docker/sa-wp-nginx-docker/data/certs:/etc/letsencrypt     -v /docker/sa-wp-nginx-docker/data/certs-data:/data/letsencrypt     certbot/certbot renew --dry-run --webroot --webroot-path=/data/letsencrypt`

And the output:

```
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/staging.mydomain.es.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Cert not due for renewal, but simulating renewal for dry run
Plugins selected: Authenticator webroot, Installer None
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for staging.mydomain.es
Using the webroot path /data/letsencrypt for all unmatched domains.
Waiting for verification...
Challenge failed for domain staging.mydomain.es
http-01 challenge for staging.mydomain.es
Cleaning up challenges
Attempting to renew cert (staging.mydomain.es) from /etc/letsencrypt/renewal/staging.mydomain.es.conf produced an unexpected error: Some challenges have failed.. Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/staging.mydomain.es/fullchain.pem (failure)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates below have not been saved.)

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/staging.mydomain.es/fullchain.pem (failure)
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates above have not been saved.)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1 renew failure(s), 0 parse failure(s)

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: staging.mydomain.es
   Type:   unauthorized
   Detail: Invalid response from
   https://staging.mydomain.es/.well-known/acme-challenge/AyxV-c2jeHKDWQlEfnzxTWSfkRXdt4GiPilSeF4xstM
   [2606:4700:30::681b:86fc]: "<!doctype html>\n<html
   lang=\"es\">\n<head>\n\t<meta charset=\"UTF-8\" />\n\t<meta
   name=\"viewport\" content=\"width=device-width, initial-sc"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.

```

**Comment by sadesarrollo** [comment]
Here you can see the content of my ./certs/renewal conf file:

```
# renew_before_expiry = 30 days
version = 0.33.1
archive_dir = /etc/letsencrypt/archive/staging.mydomain.es
cert = /etc/letsencrypt/live/staging.mydomain.es/cert.pem
privkey = /etc/letsencrypt/live/staging.mydomain.es/privkey.pem
chain = /etc/letsencrypt/live/staging.mydomain.es/chain.pem
fullchain = /etc/letsencrypt/live/staging.mydomain.es/fullchain.pem

# Options used in the renewal process
[renewalparams]
authenticator = webroot
account = 927948f4f23f575ce4f837843853e441
webroot_path = /data/letsencrypt,
server = https://acme-v02.api.letsencrypt.org/directory
[[webroot_map]]
staging.mydomain.es = /data/letsencrypt
```

**Comment by sadesarrollo** [comment]
I don't know if it could be a permission problem.. I tried giving 777 permission on my certs-data folder to no avail... please help.

**Comment by mjstealey** [comment]
>  To fix these errors, please make sure that your domain name was
>    entered correctly and the DNS A/AAAA record(s) for that domain
>    contain(s) the right IP address.

The error being shown is due to a missing A-record for `staging.mydomain.es` (cannot be found in DNS). The site must be DNS resolvable for Certbot to issue or renew a certificate. Basically the URL [https://staging.mydomain.es/.well-known/...]() is unreachable from the public internet, so Certbot cannot interact with the site to perform it's checks.

From a permissions point of view, all certificate related files should be owned by `root` and should not be moved around after generation. Certbot will use it's own versioning and symlinks to keep track of which certificates are valid for that period of time. Reference: [https://certbot.eff.org/docs/using.html#where-are-my-certificates](https://certbot.eff.org/docs/using.html#where-are-my-certificates)

**Comment by Richacinas** [comment]
Hi have the same problem. It is not about DNS.

The problem is that the file is not being placed on `.../.well-known/acme-challenge`

Shouldn't it exist there?

**Comment by mjstealey** [comment]
Have converted to using: https://github.com/RENCI-NRIG/ez-letsencrypt
