### ISSUE TITLE
Whether can provide a PHP template of the conf

### ISSUE THREAD

**Issue by Linsanxian** [mjstealey/wordpress-nginx-docker#34]
wordpress:
    image: wordpress:${WORDPRESS_VERSION:-php7.3-fpm}
    container_name: wordpress
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini

I want to edit the php.conf.Ini 
can provide an example

thanks!

**Comment by Forticas** [comment]
need same thing please
