### ISSUE TITLE
php.ini

### ISSUE THREAD

**Issue by digitalgeneralist** [mjstealey/wordpress-nginx-docker#38]
Doesn't matter what I try some how I cant set parameter for upload_max_filesize  i trie docekr-composer file tried into the config folder ... nothing works out

**Comment by digitalgeneralist** [comment]
@Fibonacci13

**Comment by amr3k** [comment]
Same issue here, Have you find a solution?

### Edit

Found [the solution](https://forums.docker.com/t/increase-upload-size-in-official-wordpress-image/100000/2) 1 minute after posting this comment 😄

**Comment by mjstealey** [comment]
> Found [the solution](https://forums.docker.com/t/increase-upload-size-in-official-wordpress-image/100000/2) 1 minute after posting this comment

In addition to the `uploads.ini` file you'd also want the Nginx configuration file to have the same parameter.
So somewhere in the `default.conf` server stanza you'd want the line `client_max_body_size 500M;` (to match the example 500 MB in your reference - just make them the same value whatever you choose)

```nginx
...

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name $host;
    index index.php index.html index.htm;
    root /var/www/html;
    server_tokens off;
    client_max_body_size 500M;                 ### <-- This line

...
```
