### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by realM1lF** [mjstealey/wordpress-nginx-docker#41]
hey there, if i try to upload an plugin zip file i run into the following message: **413 Request Entity Too Large**

Can someone please help?

thank you very much

**Comment by mjstealey** [comment]
Have included `config/uploads.ini` so you can customize upload file size and timeout parameters

reference: https://github.com/mjstealey/wordpress-nginx-docker/blob/master/config/uploads.ini
