### ISSUE TITLE
Add phpmyadmin

### ISSUE THREAD

**Issue by vpotap** [mjstealey/wordpress-nginx-docker#7]
Would it be possible to add phpmyadmin to docker-compose ?

**Comment by mjstealey** [comment]
@vpotap - It looks like it could be pretty straight forward to do. The "official" phpmyadmin image looks to live here: https://hub.docker.com/r/phpmyadmin/phpmyadmin/

Based on the description it looks like you'd want to
- Set credentials to correspond to those used for your Wordpress deployment
  - ` MYSQL_ROOT_PASSWORD` - This variable is mandatory and specifies the password that will be set for the root superuser account.
  - `MYSQL_USER`, `MYSQL_PASSWORD` - These variables are optional, used in conjunction to create a new user and to set that user's password.
- Update Nginx configuration to handle communication between phpmyadmin and the world
  - map `phpmyadmin:8080` to a port you want to expose publicly 

I'll work on starting a wiki for this repository with examples of this for reference when I get some time.

**Comment by nkondra** [comment]
@vpotap - It is super easy! I am simply adding the docker image adminer, which is phpmyadmin under the hood.

```
adminer:
    image: adminer
    restart: always
    links:
      - mysql
    ports:
      - 8080:8080
```

**Comment by czuli** [comment]
#31

**Comment by mjstealey** [comment]
admirer is now part of the docker-compose definition
